version: '3.0'

services:
  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: proffy

volumes:
  db_data: